In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('../Data/bank_note_data.txt',delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:,-1]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X= features
y= labels

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
len(X_train)

919

In [15]:
len(y_train)

919

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
scaled_X_train = scaler_object.transform(X_train)

In [23]:
scaled_X_test = scaler_object.transform(X_test)

In [24]:
scaled_X_train.max()

1.0000000000000002

In [26]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [27]:
from keras.models import Sequential
from keras.layers import Dense


In [28]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [29]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [30]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 1s - loss: 0.6858 - accuracy: 0.5996
Epoch 2/50
 - 0s - loss: 0.6782 - accuracy: 0.6931
Epoch 3/50
 - 0s - loss: 0.6687 - accuracy: 0.7225
Epoch 4/50
 - 0s - loss: 0.6592 - accuracy: 0.7356
Epoch 5/50
 - 0s - loss: 0.6484 - accuracy: 0.7356
Epoch 6/50
 - 0s - loss: 0.6363 - accuracy: 0.7378
Epoch 7/50
 - 0s - loss: 0.6226 - accuracy: 0.7432
Epoch 8/50
 - 0s - loss: 0.6080 - accuracy: 0.7465
Epoch 9/50
 - 0s - loss: 0.5919 - accuracy: 0.7454
Epoch 10/50
 - 0s - loss: 0.5754 - accuracy: 0.7606
Epoch 11/50
 - 0s - loss: 0.5584 - accuracy: 0.7628
Epoch 12/50
 - 0s - loss: 0.5398 - accuracy: 0.7737
Epoch 13/50
 - 0s - loss: 0.5202 - accuracy: 0.7900
Epoch 14/50
 - 0s - loss: 0.5022 - accuracy: 0.7965
Epoch 15/50
 - 0s - loss: 0.4840 - accuracy: 0.8107
Epoch 16/50
 - 0s - loss: 0.4671 - accuracy: 0.8150
Epoch 17/50
 - 0s - loss: 0.4501 - accuracy: 0.8357
Epoch 18/50
 - 0s - loss: 0.4341 - accuracy: 0.8455
Epoch 19/50
 - 0s - loss: 0.4179 - accuracy: 0.8607
Epoch 20/50
 - 0s - l

In [32]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [34]:
model.metrics_names

['loss', 'accuracy']

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [36]:
prediction = model.predict_classes(scaled_X_test)

In [38]:
confusion_matrix(y_test,prediction)

array([[253,   4],
       [ 15, 181]])

In [39]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

         0.0       0.94      0.98      0.96       257
         1.0       0.98      0.92      0.95       196

    accuracy                           0.96       453
   macro avg       0.96      0.95      0.96       453
weighted avg       0.96      0.96      0.96       453



In [40]:
model.save('mysupermodel.h5')

In [41]:
from keras.models import load_model

In [42]:
new_model = load_model('mysupermodel.h5')

In [43]:
new_model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    