In [1]:
pip install gym

     |████████████████████████████████| 1.6MB 3.0MB/s eta 0:00:01
     |████████████████████████████████| 1.0MB 3.9MB/s eta 0:00:01
  Created wheel for gym: filename=gym-0.16.0-cp37-none-any.whl size=1648674 sha256=ea9c255f5424fd7259db715c7f509105eac9e1248d444c7d41060b18ad32d29c
  Stored in directory: /Users/vishalsingh/Library/Caches/pip/wheels/15/40/40/af7ba6503a4c681c222e7640f7589c1d373a7af64dd1536547
Successfully built gym
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v0")

In [4]:
action_space_size = env.action_space.n  #column
state_space_size = env.observation_space.n #row

q_table = np.zeros((state_space_size,action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [10]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state,reward,done,info = env.step(action)
        
        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done==True:
            break
            
        exploration_rate = min_exploration_rate +(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
        rewards_all_episodes.append(rewards_current_episode)
        
        
   
print("Q Table")
print(q_table)
        
        

Q Table
[[0.59857763 0.53181168 0.49289717 0.52710397]
 [0.18913509 0.31834592 0.29238293 0.54630603]
 [0.40221379 0.39979806 0.40016804 0.49712868]
 [0.26336087 0.25925394 0.29466394 0.46126894]
 [0.61495588 0.4130312  0.25812351 0.31239577]
 [0.         0.         0.         0.        ]
 [0.16950561 0.16450758 0.36265518 0.16134047]
 [0.         0.         0.         0.        ]
 [0.38091348 0.42767386 0.36440952 0.6397474 ]
 [0.44629861 0.69194013 0.31441919 0.44628196]
 [0.62183075 0.49851811 0.31418459 0.27623325]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.56106724 0.46231319 0.79243203 0.51806366]
 [0.70497927 0.88641307 0.74791715 0.78515476]
 [0.         0.         0.         0.        ]]


rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("Average reward per thousand episodes")
for r in rewards_per_thousand_episodes:
    print(count,":",str(sum(r/1000)))
    count+=1000
    
 

In [14]:
for episode in range(5):
    state = env.reset()
    done=False
    print("*****Episode - ",episode+1,"****\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state,reward,done,info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("You reached the goal")
                time.sleep(3)
            else:
                print("You fell through a hole")
                time.sleep(3)
                
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()
                
                
            
                
                

  (Down)
SFFF
FHFH
FFFH
HFFG
You reached the goal
