<a href="https://colab.research.google.com/github/sendmail123/DataScience/blob/master/Pytorch/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [0]:
import torch

In [0]:
w = torch.tensor(3.0,requires_grad=True)
b = torch.tensor(1.0,requires_grad=True)


In [0]:
def forward(x):
  y = w*x+b
  return y

In [6]:
x = torch.tensor([[2],[4]])
forward(x)

tensor([[ 7.],
        [13.]], grad_fn=<AddBackward0>)

In [0]:
from torch.nn import Linear

In [8]:
torch.manual_seed(1)
model = Linear(in_features=1,out_features=1)
print(model.bias,model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [10]:
x=torch.tensor([2.0])
print(model(x))

tensor([0.5891], grad_fn=<AddBackward0>)
