<a href="https://colab.research.google.com/github/sendmail123/DataScience/blob/master/Pytorch/TensorCrashCourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [0]:
import torch
import numpy as np 

In [3]:
v = torch.tensor([1,2,3,4,5,6])
print (v)

tensor([1, 2, 3, 4, 5, 6])


In [4]:
v[1:4]

tensor([2, 3, 4])

In [5]:
f = torch.FloatTensor([1,2,3,4,5,6])
print (f.size())

torch.Size([6])


In [6]:
v.view(2,-1)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x = torch.arange(0,18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [22]:
x[1,0:2,0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [24]:
mat_a = torch.tensor([3,4,7,2,9,-2]).view(2,3)
mat_a

tensor([[ 3,  4,  7],
        [ 2,  9, -2]])

In [25]:
mat_b = torch.tensor([5,3,0,-1,2,8]).view(3,2)
mat_b

tensor([[ 5,  3],
        [ 0, -1],
        [ 2,  8]])

In [26]:
torch.matmul(mat_a,mat_b)

tensor([[ 29,  61],
        [  6, -19]])

In [27]:
x =torch.tensor(2.0,requires_grad=True)
y = 9*x**4 + 2*x**3 + 3*x**2 +6*x +1
y.backward()
x.grad

tensor(330.)